1.Create Tablespace
------------------------
CREATE TABLESPACE tbs_quiz_perm_01
  DATAFILE 'tbs_quiz_perm_01.dat' 
    SIZE 1G
  ONLINE;

CREATE TEMPORARY TABLESPACE tbs_quiz_temp_01
  TEMPFILE 'tbs_quiz_temp_01.dbf'
    SIZE 10M
    AUTOEXTEND ON;
    
CREATE UNDO TABLESPACE tbs_quiz_undo_01
  DATAFILE 'tbs_quiz_undo_01.f'
    SIZE 20M 
    AUTOEXTEND ON
  RETENTION GUARANTEE;
    
2.Create Database Schema user
----------------------------
CREATE USER quiz
  IDENTIFIED BY shreya14
  DEFAULT TABLESPACE "SYSTEM"
--  TEMPORARY TABLESPACE tbs_quiz_temp_01
  QUOTA 750M on "SYSTEM";
  
3.Grant privileges to create objects for user
--------------------------------------------
GRANT create session TO quiz;
GRANT create table TO quiz;
GRANT create view TO quiz;
GRANT create any trigger TO quiz;
GRANT create any procedure TO quiz;
GRANT create sequence TO quiz;
GRANT create synonym TO quiz;  

3.create Sequences
CREATE SEQUENCE  "SYSTEM"."TEST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1039 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "SYSTEM"."USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1013 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "SYSTEM"."QUESTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1013 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
CREATE SEQUENCE  "SYSTEM"."OPTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1013 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
4.Create Tables
-------------------------------------------------

  CREATE TABLE "QUIZ"."USERS"
   (	"EMAIL" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"USER_ID" NUMBER, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 1 NOT NULL ENABLE, 
	"ROLE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USER_PK" PRIMARY KEY ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  CREATE TABLE "QUIZ"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LAST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"SALARY" NUMBER(8,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  select */*insert*/ from employees;
  select */*insert*/ from users;
  
  
  --SELECT * FROM USER_CONSTRAINTS where constraint_name = 'QUESTION_TESTS_FK';
  CREATE TABLE "SYSTEM"."QUESTIONS_TESTS" 
   (	"QUESTION_ID" NUMBER, 
	"TEST_ID" NUMBER, 
	"QUESTION" VARCHAR2(150 CHAR) NOT NULL ENABLE, 
	"OPTIONS" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 1 NOT NULL ENABLE, 
	"ROW_TYPE" CHAR(20 CHAR) DEFAULT 'QUESTION' NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "QUESTIONS_TESTS_PK" PRIMARY KEY ("TEST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "QUESTION_TESTS_FK" FOREIGN KEY ("TEST_ID")
	  REFERENCES "SYSTEM"."TESTS" ("TEST_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  ALTER TABLE "SYSTEM"."QUESTIONS_TESTS" DROP COLUMN  "ROW_TYPE";
  ALTER TABLE "SYSTEM"."QUESTIONS_TESTS" ADD "DISPLAY_ORDER" NUMBER;
  
  ALTER TABLE "SYSTEM"."QUESTIONS_TESTS" DROP COLUMN "OPTIONS";
  ALTER TABLE "SYSTEM"."QUESTIONS_TESTS" ADD "QUESTION_TYPE" NUMBER;
  ALTER TABLE "SYSTEM"."QUESTIONS_TESTS" MODIFY  "DISPLAY_ORDER" DEFAULT 0;
  ALTER TABLE OPTIONS_QUESTIONS RENAME COLUMN OPTION TO OPTION_DESC;
  
  ALTER TABLE "SYSTEM"."QUESTIONS_TESTS" DROP CONSTRAINT "QUESTIONS_TESTS_PK";
  ALTER TABLE "SYSTEM"."QUESTIONS_TESTS" ADD CONSTRAINT  "QUESTIONS_TESTS_PK" PRIMARY KEY ("QUESTION_ID");
  
  ALTER TABLE "SYSTEM"."QUESTIONS_TESTS" MODIFY "QUESTION_TYPE" VARCHAR2(20);
  
  CREATE TABLE "SYSTEM"."OPTIONS_QUESTIONS" 
   (	"OPTION_ID" NUMBER, 
	"QUESTION_ID" NUMBER, 
	"OPTION" VARCHAR2(150 CHAR) NOT NULL ENABLE, 
	"ENABLED" CHAR(1 BYTE) DEFAULT 1 NOT NULL ENABLE, 
	"DISPLAY_ORDER" NUMBER NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "OPTIONS_QUESTIONS_PK" PRIMARY KEY ("OPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "OPTIONS_QUESTION_FK" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SYSTEM"."QUESTIONS_TESTS" ("QUESTION_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  ALTER TABLE OPTIONS_QUESTIONS RENAME COLUMN "OPTION" TO OPTION_DESC;
  ALTER TABLE OPTIONS_QUESTIONS ADD ("ANSWER" CHAR(1) DEFAULT 'N');
  select * from OPTIONS_QUESTIONS;
 
  
   CREATE TABLE "SYSTEM"."ANSWER_QUESTIONS" 
   (	
    "OPTION_ID" NUMBER, 
	"QUESTION_ID" NUMBER,
 	"ENABLED" CHAR(1 BYTE) DEFAULT 1 NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "ANSWER_QUESTIONS_PK" PRIMARY KEY ("OPTION_ID","QUESTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "ANSWER_QUESTIONS_FK" FOREIGN KEY ("QUESTION_ID")
	  REFERENCES "SYSTEM"."QUESTIONS_TESTS" ("QUESTION_ID") ENABLE,
	 CONSTRAINT "ANSWER_OPTIONS_FK" FOREIGN KEY ("OPTION_ID")
	  REFERENCES "SYSTEM"."OPTIONS_QUESTIONS" ("OPTION_ID") ENABLE
      
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ; 
  

Steps to change password for SYSTEM schema database
----------------------------------------
1.Open command prompt, type sqlplus and press enter
2.Username: SYSTEM password: <current password>
3.ALTER USER SYSTEM IDENTIFIED BY <new password>;
Angular Example
https://stackblitz.com/edit/angular-reactive-forms?file=app%2Fapp.component.html